"""
Created on Sat Jul 26 20:49:41 2018

@author: Ivan A. Maidana
"""

import random
import numpy as np

FIGURITAS_PARA_COMPLETAR_EL_ALBUM = 6
VECES_QUE_SE_COMPLETARON_LOS_ALBUNES = 10
ALBUM_LLENO = np.arange (1, FIGURITAS_PARA_COMPLETAR_EL_ALBUM + 1)
REGISTRO_DE_LAS_REPETICIONES = []

for repetir in range (VECES_QUE_SE_COMPLETARON_LOS_ALBUNES):
    def JUGADA (ALBUM):
        COUNT = 0
        while all (ALBUM) != all (ALBUM_LLENO):
            DADO = random.randint (1, FIGURITAS_PARA_COMPLETAR_EL_ALBUM)
            COUNT = COUNT + 1
            if ALBUM [DADO -1] == 0:
                ALBUM [DADO -1] = DADO
        return COUNT
    
    ALBUM_POR_LLENAR = [0] * FIGURITAS_PARA_COMPLETAR_EL_ALBUM
    ALBUM = JUGADA (ALBUM_POR_LLENAR)
    REGISTRO_DE_LAS_REPETICIONES.append (ALBUM)
	
PROMEDIO = np.mean (REGISTRO_DE_LAS_REPETICIONES, dtype = int)

def CANTIDAD (promedio_obtenido, CANTIDAD_QUE_TIENE_UN_PAQUETE):
    PAQUETES_A_COMPRAR = promedio_obtenido / CANTIDAD_QUE_TIENE_UN_PAQUETE
    return PAQUETES_A_COMPRAR
PAQUETES_1 = CANTIDAD (PROMEDIO, 5)
PAQUETES_2 = int (PAQUETES_1)

def COSTO (PAQUETES_A_COMPRAR, PRECIO_UNIDAD_PAQUETES):
    PESOS_ARG = PAQUETES_A_COMPRAR * PRECIO_UNIDAD_PAQUETES
    return PESOS_ARG
COSTO_1 = COSTO (PAQUETES_2, 14)
COSTO_2 = int (COSTO_1)
